var a = "douce";
var b = "giramata";
console.log(a+b);
let height = 180;
let anotherheight = height;
let weight;
console.log(height);
console.log(anotherheight);
weight = 70;
console.log(weight);
let stpes = 100;
console.log(stpes);
stpes = 120;
console.log(stpes);
stpes = stpes + 200;
console.log(stpes);
